export const ACTION_CHANGE_TOKEN = 'ACTION_CHANGE_TOKEN'
export const ACTION_CHANGE_USERDATA = 'ACTION_CHANGE_USERDATA'
export const ACTION_CHANGE_CLIENT = 'ACTION_CHANGE_CLIENT'
export const ACTION_SET_ADAPTER = 'ACTION_SET_ADAPTER'